In [1]:
import pandas as pd

In [53]:
# create
data = {
    "Name": ["a", "b", "c"],
    "Age": [27, 25, 32]
}

df = pd.DataFrame(data)
df

  Name  Age
0    a   27
1    b   25
2    c   32

In [66]:
#read
df = pd.read_csv("./data.csv")
df

      Name  Age  Salary
0    Hasan   32    1000
1      Ali   33    4000
2    Vahid   32    2500
3   Behnam   33    3400
4  Mahmoud   30    2400
5    Zahra   28    3300
6   Maryam   28    2700

In [6]:
df.head()

      Name  Age  Salary
0    Hasan   32    1000
1      Ali   33    4000
2    Vahid   32    2500
3   Behnam   33    3400
4  Mahmoud   30    2400

In [7]:
df.describe()

             Age       Salary
count   7.000000     7.000000
mean   30.857143  2757.142857
std     2.193063   960.654539
min    28.000000  1000.000000
25%    29.000000  2450.000000
50%    32.000000  2700.000000
75%    32.500000  3350.000000
max    33.000000  4000.000000

In [12]:
df["Salary"]

0    1000
1    4000
2    2500
3    3400
4    2400
5    3300
6    2700
Name: Salary, dtype: int64

In [21]:
df.iloc[4,2]

np.int64(2400)

In [22]:
#filter
fil= df[df["Salary"]>2500]
fil

     Name  Age  Salary
1     Ali   33    4000
3  Behnam   33    3400
5   Zahra   28    3300
6  Maryam   28    2700

In [28]:
# sort
sort = df.sort_values("Salary", ascending=True)
sort

      Name  Age  Salary
0    Hasan   32    1000
4  Mahmoud   30    2400
2    Vahid   32    2500
6   Maryam   28    2700
5    Zahra   28    3300
3   Behnam   33    3400
1      Ali   33    4000

In [29]:
df

      Name  Age  Salary
0    Hasan   32    1000
1      Ali   33    4000
2    Vahid   32    2500
3   Behnam   33    3400
4  Mahmoud   30    2400
5    Zahra   28    3300
6   Maryam   28    2700

In [30]:
# subset
subset = df.loc[2:4, ["Name", "Age"]]
subset

      Name  Age
2    Vahid   32
3   Behnam   33
4  Mahmoud   30

In [31]:
#group
group = df.groupby("Age")
group

In [32]:
df

      Name  Age  Salary
0    Hasan   32    1000
1      Ali   33    4000
2    Vahid   32    2500
3   Behnam   33    3400
4  Mahmoud   30    2400
5    Zahra   28    3300
6   Maryam   28    2700

In [33]:
group.count()

     Name  Salary
Age
28      2       2
30      1       1
32      2       2
33      2       2

In [46]:
# add a new column
df["test"] = [1, 2, 3, 4, 5, 6, 7]
df

         Age  Salary  test
Name
Hasan     32    1000     1
Ali       33    4000     2
Vahid     32    2500     3
Behnam    33    3400     4
Mahmoud   30    2400     5
Zahra     28    3300     6
Maryam    28    2700     7

In [47]:
df

         Age  Salary  test
Name
Hasan     32    1000     1
Ali       33    4000     2
Vahid     32    2500     3
Behnam    33    3400     4
Mahmoud   30    2400     5
Zahra     28    3300     6
Maryam    28    2700     7

In [48]:
# Check if the column "test" exists before attempting to drop it

df.drop("test", axis=1, inplace=True)

df

         Age  Salary
Name
Hasan     32    1000
Ali       33    4000
Vahid     32    2500
Behnam    33    3400
Mahmoud   30    2400
Zahra     28    3300
Maryam    28    2700

In [63]:
len(df)

7

In [75]:
# add a new row

df.loc[len(df)]={"Name": "Test",
                 "Age": 22}



df

      Name  Age  Salary
0    Hasan   32  1000.0
1      Ali   33  4000.0
2    Vahid   32  2500.0
3   Behnam   33  3400.0
4  Mahmoud   30  2400.0
5    Zahra   28  3300.0
6   Maryam   28  2700.0
7     Test   22     NaN

In [ ]:
df.drop(7, axis=0, inplace=True)

In [78]:
df

      Name  Age  Salary
0    Hasan   32  1000.0
1      Ali   33  4000.0
2    Vahid   32  2500.0
3   Behnam   33  3400.0
4  Mahmoud   30  2400.0
5    Zahra   28  3300.0
6   Maryam   28  2700.0
7     Test   22     NaN

In [76]:
df.isna()

    Name    Age  Salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False
7  False  False    True

In [77]:
df1= df.dropna()
df1

      Name  Age  Salary
0    Hasan   32  1000.0
1      Ali   33  4000.0
2    Vahid   32  2500.0
3   Behnam   33  3400.0
4  Mahmoud   30  2400.0
5    Zahra   28  3300.0
6   Maryam   28  2700.0

In [79]:
df2 = df.fillna(0)
df2

      Name  Age  Salary
0    Hasan   32  1000.0
1      Ali   33  4000.0
2    Vahid   32  2500.0
3   Behnam   33  3400.0
4  Mahmoud   30  2400.0
5    Zahra   28  3300.0
6   Maryam   28  2700.0
7     Test   22     0.0

In [80]:
# write

df.to_csv("new_data.csv")